src/Volunteia/Controllers/UserActionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Volunteia.Models;

namespace Volunteia.Controllers
{
    public class UserActionsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly HttpClient _httpClient;

        public UserActionsController(AppDbContext context, HttpClient httpClient)
        {
            _context = context;
            _httpClient = httpClient;   
        }

        // GET: UserActions
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserActions.ToListAsync());
        }

        // GET: UserActions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAction = await _context.UserActions
                .FirstOrDefaultAsync(m => m.ActionId == id);
            if (userAction == null)
            {
                return NotFound();
            }

            return View(userAction);
        }

        // GET: UserActions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserActions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ActionId,Name,Patrocinador,ActionDate,ActionBio,ODS,ActionStatus,VolunteersTotal,NumberOfPeopleHelped,Rate")] UserAction userAction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userAction);
                await _context.SaveChangesAsync();
                
                var actionService = new ActionService(userAction, _httpClient); // Supondo que você tenha um construtor adequado
                var result = await actionService.PublishActionAsync(userAction.Name, userAction.ActionBio);

                if (result.Equals("Aprovado"))
                {
                    userAction.ActionStatus = ActionStatus.Ativa;
                    _context.UserActions.Update(userAction);
                    await _context.SaveChangesAsync();
                    return Ok($"Ação aprovada e publicada. {result}");
                }
                else
                {
                    userAction.ActionStatus = ActionStatus.Aguardandoaprovação;
                    return Ok($"Ação aguardando moderação. {result}");
                }
                //return RedirectToAction(nameof(Index));
            }

            return View(userAction);
        }
        
        // GET: UserActions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAction = await _context.UserActions.FindAsync(id);
            if (userAction == null)
            {
                return NotFound();
            }
            return View(userAction);
        }

        // POST: UserActions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ActionId,Name,Patrocinador,ActionDate,ActionBio,ODS,ActionStatus,VolunteersTotal,NumberOfPeopleHelped,Rate")] UserAction userAction)
        {
            if (id != userAction.ActionId)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userAction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserActionExists(userAction.ActionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userAction);
        }

        // GET: UserActions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAction = await _context.UserActions
                .FirstOrDefaultAsync(m => m.ActionId == id);
            if (userAction == null)
            {
                return NotFound();
            }

            return View(userAction);
        }

        // POST: UserActions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userAction = await _context.UserActions.FindAsync(id);
            if (userAction != null)
            {
                _context.UserActions.Remove(userAction);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserActionExists(int id)
        {
            return _context.UserActions.Any(e => e.ActionId == id);
        }
    }
}

src/Volunteia/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Volunteia.Models;

namespace Volunteia.Controllers
{
    public class UsersController : Controller
    {
        private readonly AppDbContext _context;

        public UsersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Senha,NumberOfActions,Email,Phone,Address,CPForCNPJ,ShortBio,IsRestricted,IsBenefactor,IsPrivate,UserStatus,Senha")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Senha = BCrypt.Net.BCrypt.HashPassword(user.Senha);
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,NumberOfActions,Email,Phone,Address,CPForCNPJ,ShortBio,IsRestricted,IsBenefactor,IsPrivate,UserStatus")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Erro de concorrência ao tentar salvar as alterações. Tente novamente.");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

src/Volunteia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Volunteia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Volunteia.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    
                </a>
            </div>
        </nav>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Volunteia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserActions" asp-action="Index">Ações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Usuários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Volunteia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>